(()=>{
const API='https://pkisjsoblyphjrdsyslk.supabase.co/functions/v1/visa-evaluation';
const form=document.getElementById('evaluationForm');if(!form)return;
const steps=[...document.querySelectorAll('.eval-step')],counter=document.getElementById('stepCounter'),bar=document.getElementById('progressBar'),back=document.getElementById('backBtn'),next=document.getElementById('nextBtn'),submit=document.getElementById('submitBtn'),gate=document.getElementById('gateMessage'),verifyState=document.getElementById('verifyState'),submitMessage=document.getElementById('submitMessage');
let current=0,sessionId='';const q=new URLSearchParams(location.search);sessionId=q.get('session_id')||'';const preview=q.get('preview')==='rising-review';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function showStep(i){current=i;steps.forEach((s,n)=>s.classList.toggle('active',n===i));counter.textContent=`Step ${i+1} of ${steps.length}`;bar.style.width=`${((i+1)/steps.length)*100}%`;back.style.visibility=i===0?'hidden':'visible';next.classList.toggle('hidden',i===steps.length-1);submit.classList.toggle('hidden',i!==steps.length-1);window.scrollTo({top:0,behavior:'smooth'});}
function validateStep(){if(preview)return true;const fields=[...steps[current].querySelectorAll('[required]')];for(const f of fields){if(!f.checkValidity()){f.reportValidity();return false;}}return true;}
async function callApi(payload){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'Unable to process your request.');e.status=r.status;throw e;}return d;}
async function verify(){if(preview){verifyState.textContent='Admin preview · No payment';gate.className='eval-message';gate.innerHTML='<strong>Rising Preview Mode</strong><br>Review the complete artist intake without payment. You can move through every step without filling required fields. Nothing can be submitted from preview mode.';form.classList.remove('hidden');submit.disabled=true;submit.textContent='Preview only — submission disabled';showStep(0);return;}if(!sessionId){gate.className='eval-message error';gate.textContent='A valid paid evaluation session is required. Please return to Visa Services and purchase the evaluation first.';verifyState.textContent='Payment required';return;}try{let d=null,lastErr=null;for(let i=0;i<5;i++){try{d=await callApi({action:'verify',session_id:sessionId});break;}catch(e){lastErr=e;if(e.status!==404)throw e;verifyState.textContent='Confirming payment…';gate.textContent='Payment received. We’re finishing the access check…';await wait(1200);}}if(!d)throw lastErr||new Error('Unable to verify payment.');if(d.submitted){gate.className='eval-message success';gate.innerHTML='<strong>This paid evaluation has already been submitted.</strong><br>Rising has your profile. Contact bookings@risingagencyllc.com if you need help.';verifyState.textContent='Already submitted';return;}verifyState.textContent='Payment verified';gate.classList.add('hidden');form.classList.remove('hidden');if(d.email&&!form.elements.email.value)form.elements.email.value=d.email;if(d.name&&!form.elements.fullLegalName.value)form.elements.fullLegalName.value=d.name;if(d.artistName&&!form.elements.artistName.value)form.elements.artistName.value=d.artistName;showStep(0);}catch(e){gate.className='eval-message error';gate.textContent=e.message+' If you just completed payment, refresh this page. If the issue continues, contact bookings@risingagencyllc.com.';verifyState.textContent='Verification issue';}}
next.addEventListener('click',()=>{if(validateStep()&&current<steps.length-1)showStep(current+1)});back.addEventListener('click',()=>{if(current>0)showStep(current-1)});
form.addEventListener('submit',async e=>{e.preventDefault();if(preview)return;if(!validateStep())return;submit.disabled=true;submit.textContent='Submitting…';submitMessage.classList.remove('hidden');submitMessage.className='eval-message';submitMessage.textContent='Submitting your evaluation securely…';const fd=new FormData(form),answers={};for(const [k,v] of fd.entries()){if(answers[k]!==undefined){answers[k]=Array.isArray(answers[k])?[...answers[k],v]:[answers[k],v]}else answers[k]=v;}try{const d=await callApi({action:'submit',session_id:sessionId,answers});if(!d.success)throw new Error(d.error||'Submission failed.');submitMessage.className='eval-message success';submitMessage.innerHTML='<strong>Evaluation submitted.</strong><br>Rising has received your profile. We’ll review the material and prepare your personalized written assessment.';submit.classList.add('hidden');back.classList.add('hidden');verifyState.textContent='Submitted';form.querySelectorAll('input,textarea,select,button').forEach(el=>el.disabled=true);}catch(err){submit.disabled=false;submit.textContent='Submit evaluation →';submitMessage.className='eval-message error';submitMessage.textContent=err.message+' Your answers remain in this browser. Please try again or contact bookings@risingagencyllc.com.';}});
verify();
})();