(()=>{
const API='https://pkisjsoblyphjrdsyslk.supabase.co/functions/v1/visa-evaluation';
const form=document.getElementById('evaluationForm');if(!form)return;
const steps=[...document.querySelectorAll('.eval-step')],counter=document.getElementById('stepCounter'),bar=document.getElementById('progressBar'),back=document.getElementById('backBtn'),next=document.getElementById('nextBtn'),submit=document.getElementById('submitBtn'),gate=document.getElementById('gateMessage'),verifyState=document.getElementById('verifyState'),submitMessage=document.getElementById('submitMessage');
const q=new URLSearchParams(location.search);const preview=q.get('preview')==='rising-review';
let current=0,sessionId=q.get('session_id')||'';
if(!preview&&!sessionId){try{sessionId=localStorage.getItem('risingVisaSessionId')||'';if(sessionId){const u=new URL(location.href);u.searchParams.set('session_id',sessionId);history.replaceState({},'',u);}}catch(_){}}
if(!preview&&sessionId){try{localStorage.setItem('risingVisaSessionId',sessionId);}catch(_){}}
let saveTimer=null,saving=false,dirty=false,verified=false;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function showStep(i,scroll=true){current=Math.max(0,Math.min(i,steps.length-1));steps.forEach((s,n)=>s.classList.toggle('active',n===current));counter.textContent=`Step ${current+1} of ${steps.length}`;bar.style.width=`${((current+1)/steps.length)*100}%`;back.style.visibility=current===0?'hidden':'visible';next.classList.toggle('hidden',current===steps.length-1);submit.classList.toggle('hidden',current!==steps.length-1);if(scroll)window.scrollTo({top:0,behavior:'smooth'});}
function validateStep(){if(preview)return true;const fields=[...steps[current].querySelectorAll('[required]')];for(const f of fields){if(!f.checkValidity()){f.reportValidity();return false;}}return true;}
function serialize(){const fd=new FormData(form),answers={_draftStep:current};for(const [k,v] of fd.entries()){if(answers[k]!==undefined){answers[k]=Array.isArray(answers[k])?[...answers[k],v]:[answers[k],v]}else answers[k]=v;}return answers;}
function restore(answers){if(!answers||typeof answers!=='object')return;for(const [k,v] of Object.entries(answers)){if(k==='_draftStep')continue;const controls=[...form.querySelectorAll(`[name="${CSS.escape(k)}"]`)];if(!controls.length)continue;const vals=Array.isArray(v)?v:[v];controls.forEach(el=>{if(el.type==='checkbox'||el.type==='radio')el.checked=vals.map(String).includes(String(el.value));else if(v!==null&&v!==undefined)el.value=String(v);});}}
function localKey(){return `risingVisaDraft:${sessionId}`;}
function saveLocal(answers){if(preview||!sessionId)return;try{localStorage.setItem(localKey(),JSON.stringify(answers));}catch(_){}}
function loadLocal(){if(preview||!sessionId)return null;try{return JSON.parse(localStorage.getItem(localKey())||'null');}catch(_){return null;}}
async function callApi(payload){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'Unable to process your request.');e.status=r.status;throw e;}return d;}
async function saveDraft(force=false){if(preview||!verified||!sessionId)return;if(saving){dirty=true;return;}if(!force&&!dirty)return;const answers=serialize();saveLocal(answers);saving=true;dirty=false;verifyState.textContent='Saving…';try{await callApi({action:'save',session_id:sessionId,answers});verifyState.textContent='Saved automatically';}catch(e){dirty=true;verifyState.textContent='Draft saved on this device';}finally{saving=false;if(dirty&&force)saveDraft(true);}}
function queueSave(){if(preview||!verified)return;dirty=true;const answers=serialize();saveLocal(answers);clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft(),800);}
async function verify(){if(preview){verifyState.textContent='Admin preview · No payment';gate.className='eval-message';gate.innerHTML='<strong>Rising Preview Mode</strong><br>Review the complete artist intake without payment. You can move through every step without filling required fields. Nothing can be submitted from preview mode.';form.classList.remove('hidden');submit.disabled=true;submit.textContent='Preview only — submission disabled';showStep(0);return;}if(!sessionId){gate.className='eval-message error';gate.textContent='A valid paid evaluation session is required. Please return to Visa Services and purchase the evaluation first.';verifyState.textContent='Payment required';return;}try{let d=null,lastErr=null;for(let i=0;i<5;i++){try{d=await callApi({action:'verify',session_id:sessionId});break;}catch(e){lastErr=e;if(e.status!==404)throw e;verifyState.textContent='Confirming payment…';gate.textContent='Payment received. We’re finishing the access check…';await wait(1200);}}if(!d)throw lastErr||new Error('Unable to verify payment.');if(d.submitted){gate.className='eval-message success';gate.innerHTML='<strong>This paid evaluation has already been submitted.</strong><br>Rising has your profile. Contact bookings@risingagencyllc.com if you need help.';verifyState.textContent='Already submitted';return;}const serverAnswers=d.answers&&typeof d.answers==='object'?d.answers:{};const hasServer=Object.keys(serverAnswers).some(k=>k!=='_draftStep');const answers=hasServer?serverAnswers:(loadLocal()||serverAnswers);restore(answers);if(d.email&&!form.elements.email.value)form.elements.email.value=d.email;if(d.name&&!form.elements.fullLegalName.value)form.elements.fullLegalName.value=d.name;if(d.artistName&&!form.elements.artistName.value)form.elements.artistName.value=d.artistName;verified=true;verifyState.textContent=hasServer?'Draft restored · Autosave on':'Payment verified · Autosave on';gate.classList.add('hidden');form.classList.remove('hidden');const savedStep=Number(answers?._draftStep);showStep(Number.isFinite(savedStep)?savedStep:0,false);}catch(e){gate.className='eval-message error';gate.textContent=e.message+' If you just completed payment, refresh this page. If the issue continues, contact bookings@risingagencyllc.com.';verifyState.textContent='Verification issue';}}
form.addEventListener('input',queueSave);form.addEventListener('change',queueSave);
next.addEventListener('click',async()=>{if(validateStep()&&current<steps.length-1){showStep(current+1);dirty=true;await saveDraft(true);}});
back.addEventListener('click',async()=>{if(current>0){showStep(current-1);dirty=true;await saveDraft(true);}});
form.addEventListener('submit',async e=>{e.preventDefault();if(preview)return;if(!validateStep())return;clearTimeout(saveTimer);await saveDraft(true);submit.disabled=true;submit.textContent='Submitting…';submitMessage.classList.remove('hidden');submitMessage.className='eval-message';submitMessage.textContent='Submitting your evaluation securely…';const answers=serialize();try{const d=await callApi({action:'submit',session_id:sessionId,answers});if(!d.success)throw new Error(d.error||'Submission failed.');try{localStorage.removeItem(localKey());localStorage.removeItem('risingVisaSessionId');}catch(_){}submitMessage.className='eval-message success';submitMessage.innerHTML='<strong>Evaluation submitted.</strong><br>Rising has received your profile. We’ll review the material and prepare your personalized written assessment.';submit.classList.add('hidden');back.classList.add('hidden');verifyState.textContent='Submitted';form.querySelectorAll('input,textarea,select,button').forEach(el=>el.disabled=true);}catch(err){submit.disabled=false;submit.textContent='Submit evaluation →';submitMessage.className='eval-message error';submitMessage.textContent=err.message+' Your answers remain saved. Please try again or contact bookings@risingagencyllc.com.';}});
window.addEventListener('beforeunload',()=>{if(!preview&&verified)saveLocal(serialize());});
verify();
})();